### ISSUE TITLE
Create CWE -> SNS -> HTTP/S Example

### ISSUE THREAD

**Issue by rjulian** [reflexivesecurity/reflex-engine#12]
For those who want to write their own parsers, just as an option, but definitely not chief thing to support.

**Comment by rot26** [comment]
We currently don't support other SNS topic subscriptions in the `reflex.yaml` so this would require editing `reflex_out` which would diverge from the generated reflex terraform.

**Comment by mcbanderson** [comment]
Closing, as I don't believe this is currently something we are looking to support. If you disagree feel free to reopen.
